repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: trailing-whitespace
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: '\.bat$'
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.19.0
  hooks:
  - id: gitleaks
    args: ["--config=.gitleaks.toml"]
